#!/bin/bash

#
# This file is a part of WebTester project
#
# Copyright (C) 2009 Sergey I. Sharybin <g.ulairi@gmail.com>
#
# Thids file can be distributed under the terms of the GNU GPL
#

### BEGIN INIT INFO
# Provides:          WebTester Server
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Script to start and stop WebTester Server
# Description:       Used to start and stop WebTester Server.
#                    This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO

# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PREFIX="/home/webtester"
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="WebTester Server"
NAME=webtester
PIDNAME="supervisor"
DAEMON=${PREFIX}/$NAME
DAEMON_ARGS="--fork --silent"
PIDFILE=${PREFIX}/var/run/$PIDNAME.pid
SCRIPTNAME=/etc/init.d/$NAME

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

VERBOSE=yes

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions

#
# Function that starts the daemon/service
#
do_start()
{
  # Return
  #   0 if daemon has been started
  #   1 if daemon was already running
  #   2 if daemon could not be started

  start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null 2>&1 \
    || return 1
  start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
    $DAEMON_ARGS > /dev/null 2>&1\
    || return 2

  sleep 1;

  if [ -e $PIDFILE ]; then
    echo "" > /dev/null;
  else
    return 2;
  fi
}

#
# Function that stops the daemon/service
#
do_stop()
{
  # Return
  #   0 if daemon has been stopped
  #   1 if daemon was already stopped
  #   2 if daemon could not be stopped
  #   other if a failure occurred

  start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME > /dev/null
  RETVAL="$?"
  [ "$RETVAL" = 2 ] && return 2

  # Wait for children to finish too if this is a daemon that forks
  # and if the daemon is only ever run from this initscript.
  # If the above conditions are not satisfied then add some other code
  # that waits for the process to drop all resources that could be
  # needed by services started subsequently.  A last resort is to
  # sleep for some time.
  start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON > /dev/null
  [ "$?" = 2 ] && return 2

  # Many daemons don't delete their pidfiles when they exit.
  if ( test "x`pidof webtester`" = "x" ); then
    rm -f $PIDFILE;
  fi;

  return "$RETVAL"
}

#
# Function that sends a SIGHUP to the daemon/service
#
do_reload() {
  #
  # If the daemon can reload its configuration without
  # restarting (for example, when it is sent a SIGHUP),
  # then implement that here.
  #
  start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
  return 0
}

#
# Compilation of LibRUN
#
# This function is neccessary because LibRUN should be
# compiled for current version of kernel, and if you
# change kernel you should recompile LibRUN.
# It is the most easy way to do this.
#
compile_librun() {
  cwd=`pwd`
  log="${PREFIX}/var/log/webtester.setup.log"

  echo "* Started compilation of librun." > ${log}

  cd "${PREFIX}/usr/src/librun"
  echo "make clean" >> ${log} && make clean && \
    echo "make" >> ${log} && make >> ${log} 2>&1 && \
    echo "* Compilation successfully completed." >> ${log} && \
    chmod 644 "${PREFIX}/usr/src/librun/librun.so";

  res=$?

  cd ${cwd}

  return ${res}
}

install_librun() {
  echo "* Installing new librun" >> "${PREFIX}/var/log/webtester.setup.log"
  cp -f ${PREFIX}/usr/src/librun/librun.so ${PREFIX}/lib
}

case "$1" in
  start)
  [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
  do_start
  case "$?" in
    0) [ "$VERBOSE" != no ] && log_end_msg 0; ;;
    1) [ "$VERBOSE" != no ] && (log_end_msg 1; echo "$NAME is already started") ;;
    2) [ "$VERBOSE" != no ] && (log_end_msg 1; echo "$NAME could not be started");;
  esac
  ;;
  stop)
  [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC"
  do_stop
  case "$?" in
    0) [ "$VERBOSE" != no ] && (echo -n " $NAME"; log_end_msg 0) ;;
    1) [ "$VERBOSE" != no ] && (log_end_msg 1; echo "$NAME is already stopped" ) ;;
    2) [ "$VERBOSE" != no ] && (log_end_msg 1; echo "$NAME could not be stopped" );;
  esac
	;;
  #reload|force-reload)
  #
  # If do_reload() is not implemented then leave this commented out
  # and leave 'force-reload' as an alias for 'restart'.
  #
  #log_daemon_msg "Reloading $DESC" "$NAME"
  #do_reload
  #log_end_msg $?
  #;;
  restart|force-reload)
  #
  # If the "reload" option is implemented then remove the
  # 'force-reload' alias
  #
  log_daemon_msg "Restarting $DESC" "$NAME"
  do_stop
  case "$?" in
    0|1)
    do_start
    case "$?" in
      0) log_end_msg 0 ;;
      1) log_end_msg 1 ;; # Old process is still running
      *) log_end_msg 1 ;; # Failed to start
    esac
    ;;
    *)
    # Failed to stop
    log_end_msg 1
    ;;
  esac
  ;;
  setup)
    stopped=false

    mkdir /home/webtester/var/log > /dev/null 2>&1 && \
      chown webtester:webtester /home/webtester/var/log > /dev/null 2>&1

    log_daemon_msg "Compiling needed libraries"
    echo -n " librun"
    compile_librun

    case "$?" in
      0)
        log_end_msg 0

        if test -f $PIDFILE; then
          echo "* Stopping webtester" >> "${PREFIX}/var/log/webtester.setup.log"
          do_stop
          stopped=true
        fi

        install_librun

        if $stopped; then
          echo "* Staring webtester" >> "${PREFIX}/var/log/webtester.setup.log"
          do_start
        fi
      ;;
      *)
        log_end_msg 1
        echo "See the file ${PREFIX}/var/log/webtester.setup.log for details."
      ;;
    esac

  ;;
  *)
  echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload|setup}" >&2
  exit 3
  ;;
esac

:
