.SILENT:

all:
	printf "%10s     %-20s\n" LINK checker
	g++ -L../../stuff/testlib -L../../stuff/testlib++ -I../../stuff/testlib -I../../stuff/testlib++ -ltestlib -ltestlib++ -o checker main.cxx

depend:	

configure:	

install:

clean:
	rm -f checker *.o

distclean:
	rm -f checker *.o

